import { ObjParser } from "../ObjLoader"
const obj = `
# WaveFront *.obj file (generated by Cheetah3D)

mtllib box.mtl

g Box
v -0.500000 -0.500000 0.500000
v -0.500000 0.500000 0.500000
v 0.500000 0.500000 0.500000
v 0.500000 -0.500000 0.500000
v 0.500000 -0.500000 -0.500000
v 0.500000 0.500000 -0.500000
v -0.500000 0.500000 -0.500000
v -0.500000 -0.500000 -0.500000

vt 0.000000 0.000000
vt 0.000000 1.000000
vt 1.000000 1.000000
vt 1.000000 0.000000

vn 0.000000 0.000000 1.000000
vn 0.000000 0.000000 -1.000000
vn -1.000000 0.000000 0.000000
vn 1.000000 0.000000 0.000000
vn 0.000000 1.000000 0.000000
vn 0.000000 -1.000000 0.000000

usemtl Material
f 6/3/4 3/2/4 4/1/4
f 4/1/4 5/4/4 6/3/4
f 6/3/5 7/2/5 2/1/5
f 2/1/5 3/4/5 6/3/5

usemtl Material.2
f 7/3/2 6/2/2 5/1/2
f 5/1/2 8/4/2 7/3/2
f 2/3/3 7/2/3 8/1/3
f 8/1/3 1/4/3 2/3/3

usemtl Material.3
f 3/3/1 2/2/1 1/1/1
f 1/1/1 4/4/1 3/3/1
f 4/3/6 1/2/6 8/1/6
f 8/1/6 5/4/6 4/3/6

usemtl default
`

const mtl = `
# WaveFront *.mtl file (generated by Cheetah3D)

newmtl default
Ns 64
Kd 0.700 0.700 0.700
Ks 1.000 1.000 1.000
Ka 0.700 0.700 0.700

newmtl Material
Ns 80.000000
Tr 1.000000
Kd 0.986246 0.007121 0.027434
Ks 1.000000 1.000000 1.000000
Ka 0.1 0.1 0.1

newmtl Material.2
Ns 80.000000
Tr 1.000000
Kd 0.065930 0.501799 0.006832
Ks 1.000000 1.000000 1.000000
Ka 0.1 0.1 0.1

newmtl Material.3
Ns 80.000000
Tr 1.000000
Kd 1.000000 1.000000 1.000000
Ks 1.000000 1.000000 1.000000
Ka 0.1 0.1 0.1
map_Kd test.png
`;



describe("ObjParser", () => {
  const parser = new ObjParser(obj);
  it("should be parsed mtllib", () => {
    expect(parser.mtllib()).toEqual({ name: "box.mtl" })
  });
  it("should be parsed groups", () => {
    const actual = parser.groups()
    expect(actual.length).toBe(1);
    expect(actual[0].name).toBe("Box")
    expect(actual[0].faces.length).toBe(12);
  });
});
